### ISSUE TITLE
在游戏内取消了一个模组的装载，退出学术端后重新进入，在进入游戏的画面完成后闪退并报错

### ISSUE THREAD

**Issue by Ninjiaazz** [CN-ARC/Mindustry-CN-ARC#71]
### Platforms

Windows

### Build

146

### Issue

闪退

### Steps to reproduce

在游戏内取消了一个模组的装载，退出学术端后重新进入，在进入游戏的画面完成后闪退并报错

### Mods used

模组刚刚全部禁止

### (Crash) logs

喜报！你的学术端崩溃了！
在确定不是你自己的问题后在这里报告: https://github.com/CN-ARC/Mindustry-CN-ARC/issues/new?labels=bug&template=bug_report.md

版本: release build 146
系统: Windows 11 x32 (x86)
Java版本: 1.8.0_381
可用内存: 247mb
核心数量: 12
Mods: 没有 (原版)

java.lang.OutOfMemoryError
	at sun.misc.Unsafe.allocateMemory(Native Method)
	at java.nio.DirectByteBuffer.<init>(Unknown Source)
	at java.nio.ByteBuffer.allocateDirect(Unknown Source)
	at arc.graphics.PixmapIO$PngReader.read(PixmapIO.java:221)
	at arc.graphics.Pixmap.loadJava(Pixmap.java:761)
	at arc.graphics.Pixmap.load(Pixmap.java:744)
	at arc.graphics.Pixmap.<init>(Pixmap.java:74)
	at arc.graphics.gl.FileTextureData.prepare(FileTextureData.java:35)
	at arc.graphics.TextureData.getPixmap(TextureData.java:47)
	at arc.graphics.g2d.TextureAtlas.lambda$getPixmap$0(TextureAtlas.java:125)
	at arc.struct.ObjectMap.get(ObjectMap.java:328)
	at arc.graphics.g2d.TextureAtlas.getPixmap(TextureAtlas.java:125)
	at arc.graphics.g2d.TextureAtlas.getPixmap(TextureAtlas.java:144)
	at mindustry.arcModule.RFuncs.blockColor(RFuncs.java:50)
	at mindustry.arcModule.RFuncs.lambda$colorizeContent$4(RFuncs.java:35)
	at arc.struct.Seq.each(Seq.java:189)
	at mindustry.arcModule.RFuncs.colorizeContent(RFuncs.java:34)
	at mindustry.ui.dialogs.DatabaseDialog.<init>(DatabaseDialog.java:45)
	at mindustry.core.UI.init(UI.java:226)
	at mindustry.ClientLauncher.update(ClientLauncher.java:223)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:40)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by squi2rel** [comment]
内存不足。加入启动参数-Xmx1G
