### ISSUE TITLE
快捷视角引发的崩溃

### ISSUE THREAD

**Issue by gszshdzz** [CN-ARC/Mindustry-CN-ARC#74]
喜报！你的学术端崩溃了！
在确定不是你自己的问题后在这里报告: https://github.com/CN-ARC/Mindustry-CN-ARC/issues/new?labels=bug&template=bug_report.md

版本: release build 146
系统: Windows 10 x64 (amd64)
Java版本: 16.0.1
可用内存: 6068mb
核心数量: 4
Mods: 没有 (原版)

java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at mindustry.arcModule.ui.QuickCameraTable.lambda$hudButton$4(QuickCameraTable.java:85)
	at arc.Events.lambda$run$2(Events.java:20)
	at arc.Events.fire(Events.java:36)
	at mindustry.core.Logic.update(Logic.java:406)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:275)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:41)

**Comment by Jackson11500** [comment]
应该修了，如果还有问题的话最好说下情形（我没找到这bug触发方式）

**Comment by gszshdzz** [comment]
> 应该修了，如果还有问题的话最好说下情形（我没找到这bug触发方式）

我在你b站视频下面说了，就是在游戏内调整快捷视角个数（调了之后不会马上有效），然后退出重进服务器一到两次

**Comment by gszshdzz** [comment]
> 应该修了，如果还有问题的话最好说下情形（我没找到这bug触发方式）

版本30764，没修好，日志多了两行
其实不用退出重进，直接调整两次就行了
`	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at mindustry.desktop.DesktopLauncher0.main(DesktopLauncher0.java:10)
`

https://github.com/CN-ARC/Mindustry-CN-ARC/assets/68946978/4de7f486-d462-409e-82dc-6e8d483be9a0

还有一个，就是用itch里面的那个启动器启动，模组浏览器和检查更新会handshake failure，如果直接双击jar或者java -jar启动，开始下载更新的时候会崩溃
`喜报！你的学术端崩溃了！
在确定不是你自己的问题后在这里报告: https://github.com/CN-ARC/Mindustry-CN-ARC/issues/new?labels=bug&template=bug_report.md

版本: release build 146
系统: Windows 11 x64 (amd64)
Java版本: 21.0.2
可用内存: 6068mb
核心数量: 4
Mods: 没有 (原版)

java.lang.NullPointerException: Cannot invoke "java.net.URL.getPath()" because the return value of "java.security.CodeSource.getLocation()" is null
	at mindustry.net.BeControl.lambda$buildTable$33(BeControl.java:218)
	at arc.scene.Element$9.changed(Element.java:988)
	at arc.scene.event.ChangeListener.handle(ChangeListener.java:13)
	at arc.scene.Element.notify(Element.java:162)
	at arc.scene.Element.fire(Element.java:133)
	at arc.scene.ui.Button.setChecked(Button.java:106)
	at arc.scene.ui.Button$1.clicked(Button.java:92)
	at arc.scene.event.ClickListener.touchUp(ClickListener.java:77)
	at arc.scene.event.InputListener.handle(InputListener.java:31)
	at arc.scene.Scene.touchUp(Scene.java:370)
	at arc.input.InputMultiplexer.touchUp(InputMultiplexer.java:136)
	at arc.input.InputEventQueue.drain(InputEventQueue.java:71)
	at arc.backend.sdl.SdlInput.update(SdlInput.java:181)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:189)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:41)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at mindustry.desktop.DesktopLauncher0.main(DesktopLauncher0.java:10)
`
@Jackson11500

**Comment by Jackson11500** [comment]
> > 应该修了，如果还有问题的话最好说下情形（我没找到这bug触发方式）
> 
> 版本30764，没修好，日志多了两行 其实不用退出重进，直接调整两次就行了 ` at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) at java.base/java.lang.reflect.Method.invoke(Method.java:580) at mindustry.desktop.DesktopLauncher0.main(DesktopLauncher0.java:10) `

我还是没能复现，怎么调也没崩啊(而且也没收到其他人说的类似问题。
而且看你这个报错不像是这个的问题，怎么反射都出来了，一般是mod才用的吧。

模组更新的问题我问下@squi2rel

**Comment by gszshdzz** [comment]
windows沙盒成功复现
视频18.8mb，github不让放，传网盘了
前面一半是快捷视角，后面是自动更新，最后面是原版测试版更新没有问题
https://www.alipan.com/s/4CM4c56LhSt

**Comment by gszshdzz** [comment]
> windows沙盒成功复现 视频18.8mb，github不让放，传网盘了 前面一半都是复制安装，后半的前面是快捷视角，后面是自动更新，最后面是原版测试版更新没有问题 https://www.alipan.com/s/4CM4c56LhSt

手机也能卡，不录屏了

**Comment by Jackson11500** [comment]
现在应该没有bug了，应该是修好了，最近都没看到有人反馈。

**Comment by gszshdzz** [comment]
> 现在应该没有bug了，应该是修好了，最近都没看到有人反馈。

不信（
还有前几天换电脑了，照样，把mdt数据文件直接全部复制的，大概跟这个没关系




喜报！你的学术端崩溃了！
在确定不是你自己的问题后在这里报告: https://github.com/CN-ARC/Mindustry-CN-ARC/issues/new?labels=bug&template=bug_report.md

版本: release build 146
学术版本: 30793
系统: Windows 11 x64 (amd64)
Java版本: 21.0.2
可用内存: 4018mb
核心数量: 32
Mods: 没有 (原版)

java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
	at mindustry.arcModule.ui.QuickCameraTable.lambda$hudButton$6(QuickCameraTable.java:101)
	at arc.Events.lambda$run$2(Events.java:20)
	at arc.Events.fire(Events.java:36)
	at mindustry.core.Logic.update(Logic.java:406)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:275)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:41)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at mindustry.desktop.DesktopLauncher0.main(DesktopLauncher0.java:10)

**Comment by gszshdzz** [comment]
> 现在应该没有bug了，应该是修好了，最近都没看到有人反馈。

另外现在30794进维泽服显示forbidden packet建议使用官方客户端，其他可以显示arc的也不会显示arc图标（鱼服），已经在一台电脑和一台手机测试，手机的是全新安装没有旧数据的
