### ISSUE TITLE
超多队pvp崩溃

### ISSUE THREAD

**Issue by gszshdzz** [CN-ARC/Mindustry-CN-ARC#76]
应该跟 4dae336ee70395392dfb88b5c9dbbcb208947c76 有关
_怎么三个issue都是我发的_

喜报！你的学术端崩溃了！
在确定不是你自己的问题后在这里报告: https://github.com/CN-ARC/Mindustry-CN-ARC/issues/new?labels=bug&template=bug_report.md

版本: release build 146
学术版本: 30779
系统: Windows 11 x64 (amd64)
Java版本: 21.0.2
可用内存: 6068mb
核心数量: 4
Mods: 没有 (原版)

java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at mindustry.arcModule.toolpack.ARCTeam$ARCTeamData.updateItems(ARCTeam.java:105)
	at mindustry.arcModule.toolpack.ARCTeam$ARCTeamData.update(ARCTeam.java:100)
	at mindustry.arcModule.toolpack.ARCTeam.lambda$update$7(ARCTeam.java:65)
	at arc.struct.Seq.each(Seq.java:189)
	at mindustry.arcModule.toolpack.ARCTeam.update(ARCTeam.java:65)
	at mindustry.arcModule.toolpack.ARCTeam.lambda$new$3(ARCTeam.java:46)
	at arc.Events.lambda$run$2(Events.java:20)
	at arc.Events.fire(Events.java:36)
	at mindustry.core.Logic.update(Logic.java:406)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:275)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:41)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at mindustry.desktop.DesktopLauncher0.main(DesktopLauncher0.java:10)

**Comment by squi2rel** [comment]
可以复现。TODO

**Comment by squi2rel** [comment]
[061be73](https://github.com/CN-ARC/Mindustry-CN-ARC/commit/061be733a0f74aaaed7d665b77e12c88de19b253)
